name: ci 
on: 
  push: 
    branches: 
      - 'main' 
jobs: 
  docker: 
    runs-on: ubuntu-latest 
    steps: 
      - 
        name: Set up QEMU 
        uses: docker/setup-qemu-action@v2 
      - 
        name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2 
      - 
        name: Login to Docker Hub 
        uses: docker/login-action@v2 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - 
        name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: '0.2' # optional
          docker_compose: 'docker-compose.build.yml' # required
          repo_token: ${{ secrets.SECRET_TOKEN }}
