# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - llano-velasco-prueba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login Docker Huub
      uses: docker/login-action@v2
      with: 
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yml
        down-flags: "--volumes"
        push: true
        build: true
        services: |
          spring
          angular
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      run: npm install
    - name: npm init
      run: npm init -y
    - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - run: 'docker-compose push'