name: ci 
on: 
  push: 
    branches: 
      - 'main' 
jobs: 
  docker: 
    runs-on: ubuntu-latest 
    steps:
      #- name: Log into registry
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin  
      # Check out the repo    
      - name: Checkout
        uses: actions/checkout@v2
      # Build the images    
      - name: Build the docker-compose stack  
        run: docker-compose -f docker-compose.yml build
      # List images that will be pushed
      - name: List images
        run: docker images
      # Push images
      #- name: Push images
      #  run: docker-compose -f examples/helix-basic-aspnetcore/docker-compose.yml -f examples/helix-basic-aspnetcore/docker-compose.override.yml push --ignore-push-failures

