# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - velasco-llano-prueba2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7fe941a61d744868b3e56a83d17fa185 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_da86e869f4a34dcdb1f87cf75390b9e3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7fe941a61d744868b3e56a83d17fa185 }}/angular:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'velasco-llano-prueba2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d923d6b68b1b4f3dac576d53dfc8894c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7fe941a61d744868b3e56a83d17fa185 }}/angular:${{ github.sha }}'