name: CI
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
          run: |
            if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI