name: CI
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: 'npm install'
      - name: Setup
        run: 'npm ci'
      - name: Test
        run: 'npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI'